version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=app-stages
      - POSTGRES_PASSWORD=app-stages
      - POSTGRES_DB=app-stages 
    volumes:
      - ./dump_BD.sql:/docker-entrypoint-initdb.d/dump_BD.sql
    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://app-stages:app-stages@db/app-stages?serverVersion=15&charset=utf8
    depends_on:
      - db

    volumes:
      - ./:/app
      - vendor:/app/vendor

  proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - app

volumes:
  vendor:
    driver: local

    